apiVersion: v1
kind: Service
metadata:
  name: {{ include "peopleapi-challenge-hs.fullname" . }}
  labels:
    {{- include "peopleapi-challenge-hs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP      
  selector:
    app.kubernetes.io/instance: {{ include "peopleapi-challenge-hs.fullname" . }}
    app.kubernetes.io/name: {{ include "peopleapi-challenge-hs.fullname" . }} 